language: c

dist: trusty
sudo: required

services:

compiler:
  - gcc

install:
  - sudo apt-get install libgnat-4.6
  - wget http://ftp.de.debian.org/debian/pool/main/m/mpclib/libmpc2_0.9-4_amd64.deb -Olibmpc2.deb
  - sudo dpkg -i libmpc2.deb
  - wget https://sourceforge.net/projects/ghdl-updates/files/Builds/ghdl-0.31/Debian/ghdl_0.31-2wheezy1_amd64.deb/download -Oghdl.deb
  - sudo dpkg -i ghdl.deb

script:
  - source toolchain/setenv.sh
# Skip building BIOS till running the cross compiler on Travis works
#  - make
  - make -C vhdl all
  - make -C vhdl test

after_success:
