language: c

dist: trusty
sudo: required

services:

compiler:
  - gcc

install:
  - ./install-deps.sh
  - ghdl --version

script:
  - source toolchain/setenv.sh
# Skip building BIOS till running the cross compiler on Travis works
#  - make
  - make -C vhdl all
  - make -C vhdl test

after_success:
