language: c

dist: trusty
sudo: required

services:

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9


install:
  - ./install-ghdl.sh
  - source setenv.sh
  - ghdl --version

script:
  - source setenv.sh
  - make bios
  - make -C vhdl all
  - make -C vhdl test


after_success:
