language: c

dist: trusty
sudo: required

services:

compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9

install:
  - ./install-deps.sh
  - ghdl --version

script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - source toolchain/setenv.sh
  - make bios
  - make -C vhdl all
  - make -C vhdl test


after_success:
