-- Generated by tools/generate-rom.pl
-- Template: https://www.xilinx.com/support/answers/8183.html

library ieee;
use ieee.std_logic_1164.all;
use work.txt_utils.all;
use work.arch_defs.all;

entity rom is
    port ( a: in std_logic_vector(31 downto 0);
           z: out std_logic_vector(31 downto 0);
           en: in std_logic
         );
    attribute syn_romstyle : string;
    attribute syn_romstyle of z : signal is "select_rom";
end rom;

architecture rtl of rom is
    begin
    process(a)
    begin
        if en = '1' then
            printf("Address = %s\n", a);
            case a is

            when X"0000_0000" => z <= B"001101_00001_00001" & X"f000"; -- ori r1, r1, 0xf000
            when X"0000_0004" => z <= B"001101_00010_00010" & X"0b00"; -- ori r1, r2, 0x0b00
            when X"0000_0008" => z <= X"08_000000"; -- j start

            when others => null;
            end case;
        end if;
    end process;
end rtl;
